-- PulseFit Supabase schema
-- Run this in Supabase SQL Editor.

create table if not exists public.users_data (
  user_id uuid primary key references auth.users(id) on delete cascade,
  public_user_id text,
  email text not null,
  username text,
  first_name text,
  last_name text,
  gender text check (gender in ('male', 'female')),
  governorate text,
  age integer,
  weight numeric,
  height numeric,
  goal text default 'maintenance',
  completed_workouts integer not null default 0,
  goals_completed integer not null default 0,
  subscription_plan text check (subscription_plan in ('monthly', 'yearly', 'lifetime')),
  subscription_status text not null default 'trial' check (subscription_status in ('trial', 'active', 'expired', 'pending')),
  subscription_expires_at timestamptz,
  account_status text not null default 'active',
  suspended_until timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.users_data add column if not exists completed_workouts integer not null default 0;
alter table public.users_data add column if not exists goals_completed integer not null default 0;
alter table public.users_data add column if not exists subscription_plan text;
alter table public.users_data add column if not exists subscription_status text not null default 'trial';
alter table public.users_data add column if not exists subscription_expires_at timestamptz;
alter table public.users_data add column if not exists public_user_id text;
alter table public.users_data add column if not exists account_status text not null default 'active';
alter table public.users_data add column if not exists suspended_until timestamptz;

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  message text not null,
  type text not null default 'system',
  read boolean not null default false,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.notifications enable row level security;
drop policy if exists "notifications_select_own" on public.notifications;
create policy "notifications_select_own" on public.notifications for select using (auth.uid() = user_id);

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  email text not null,
  plan text not null check (plan in ('monthly', 'yearly', 'lifetime')),
  amount numeric,
  receipt_url text,
  receipt_data_url text,
  status text not null default 'pending' check (status in ('pending', 'approved', 'declined')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  reviewed_at timestamptz
);

insert into storage.buckets (id, name, public)
values ('payment-proofs', 'payment-proofs', false)
on conflict (id) do update set public = false;

drop policy if exists "payment_proofs_insert_own" on storage.objects;
create policy "payment_proofs_insert_own" on storage.objects for insert to authenticated
with check (bucket_id = 'payment-proofs' and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists "payment_proofs_select_own" on storage.objects;
create policy "payment_proofs_select_own" on storage.objects for select to authenticated
using (bucket_id = 'payment-proofs' and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists "payment_proofs_public_read" on storage.objects;

create table if not exists public.workouts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  equipment text,
  duration_minutes integer,
  exercises jsonb not null default '[]'::jsonb,
  completed_at timestamptz,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.users_data enable row level security;
alter table public.payments enable row level security;
alter table public.workouts enable row level security;

drop policy if exists "users_data_select_own" on public.users_data;
create policy "users_data_select_own" on public.users_data for select using (auth.uid() = user_id);

drop policy if exists "users_data_insert_own" on public.users_data;
create policy "users_data_insert_own" on public.users_data for insert with check (auth.uid() = user_id);

drop policy if exists "users_data_update_own" on public.users_data;
create policy "users_data_update_own" on public.users_data for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "payments_select_own" on public.payments;
create policy "payments_select_own" on public.payments for select using (auth.uid() = user_id);

drop policy if exists "payments_insert_own" on public.payments;
create policy "payments_insert_own" on public.payments for insert with check (auth.uid() = user_id);

drop policy if exists "workouts_select_own" on public.workouts;
create policy "workouts_select_own" on public.workouts for select using (auth.uid() = user_id);

drop policy if exists "workouts_insert_own" on public.workouts;
create policy "workouts_insert_own" on public.workouts for insert with check (auth.uid() = user_id);

drop policy if exists "workouts_update_own" on public.workouts;
create policy "workouts_update_own" on public.workouts for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "workouts_delete_own" on public.workouts;
create policy "workouts_delete_own" on public.workouts for delete using (auth.uid() = user_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.users_data (user_id, email, username, first_name, last_name, gender, governorate, age, weight, height, goal)
  values (
    new.id,
    new.email,
    new.raw_user_meta_data ->> 'username',
    new.raw_user_meta_data ->> 'first_name',
    new.raw_user_meta_data ->> 'last_name',
    new.raw_user_meta_data ->> 'gender',
    new.raw_user_meta_data ->> 'governorate',
    nullif(new.raw_user_meta_data ->> 'age', '')::integer,
    nullif(new.raw_user_meta_data ->> 'weight', '')::numeric,
    nullif(new.raw_user_meta_data ->> 'height', '')::numeric,
    coalesce(new.raw_user_meta_data ->> 'goal', 'maintenance')
  )
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Enable Supabase Realtime for the cloud Telegram worker.
alter publication supabase_realtime add table public.users_data;
alter publication supabase_realtime add table public.payments;
